import {execFileSync} from 'node:child_process';
import {readFile,writeFile,readdir} from 'node:fs/promises';
import {join} from 'node:path';
import {homedir} from 'node:os';
import assert from 'node:assert/strict';
const p=JSON.parse(await readFile('.lab/b2b-starter-latest.json','utf8'));
const site=JSON.parse(await readFile(join(p.run,'artifacts-primary/site.json'),'utf8'));
const cli=process.env.PLAYWRIGHT_CLI??join(homedir(),'.codex/skills/playwright/scripts/playwright_cli.sh');
const out='docs/acceptance/b2b-redesign',session='b2b-starter';
execFileSync(cli,['--session',session,'--raw','open',p.urls.primary+'/wp-admin/'],{stdio:'pipe',timeout:90000});
// eslint-disable-next-line preserve-caught-error -- Command errors contain private login arguments; retain redacted output only.
function call(code){try{return JSON.parse(execFileSync(cli,['--session',session,'--raw','run-code',code],{encoding:'utf8',timeout:120000,maxBuffer:4*1024*1024}));}catch(error){throw new Error(String(error.stdout||'Browser failed').replaceAll(p.adminPassword,'[redacted]'));}}
const wp=code=>execFileSync('docker',['compose','-p',p.project,'-f',p.compose,'exec','-T','primary','php','/tools/wp','--allow-root','eval',code],{encoding:'utf8',timeout:60000});
const id=site.products.yhd08,home=site.pages.home,term=site.categories['mini-excavator'];
const original=JSON.parse(wp(`echo wp_json_encode(['model'=>get_field('model',${id}),'template'=>get_post_meta(${id},'_wp_page_template',true),'body'=>get_post_field('post_content',${id}),'image'=>get_post_thumbnail_id(${id}),'home'=>get_post_field('post_content',${home}),'layout'=>get_field('category_layout','hd_category_${term}')]);`));
const result={testedAt:new Date().toISOString(),checks:{}};
try{
 call(`async(page)=>{await page.setViewportSize({width:1440,height:1000});await page.goto('${p.urls.primary}/wp-admin/post.php?post=${id}&action=edit');if(page.url().includes('wp-login')){await page.getByRole('textbox',{name:'Username or Email Address'}).fill('admin');await page.getByRole('textbox',{name:'Password',exact:true}).fill(${JSON.stringify(p.adminPassword)});await page.getByRole('button',{name:'Log In',exact:true}).click();}const d=page.getByRole('dialog',{name:'Welcome to the editor'});if(await d.count())await d.getByRole('button',{name:'Close'}).click();await page.getByRole('button',{name:'Save',exact:true}).waitFor();return {ready:true};}`);
 result.checks.templatePicker=call(`async(page)=>{if(!(await page.getByRole('button',{name:'Template options',exact:true}).isVisible()))await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Template options',exact:true}).click();await page.getByRole('menuitem',{name:'Change template',exact:true}).click();const names=await page.getByRole('listbox',{name:'Templates'}).getByRole('option').allTextContents();await page.getByRole('option',{name:'Product — Standard',exact:true}).click();await page.getByRole('button',{name:'Save',exact:true}).click();await page.waitForFunction(()=>!wp.data.select('core/editor').isSavingPost()&&!wp.data.select('core/editor').isEditedPostDirty());return {names,selected:await page.evaluate(()=>wp.data.select('core/editor').getEditedPostAttribute('template'))};}`);
 assert.equal(result.checks.templatePicker.selected,'product-standard');
 result.checks.field=call(`async(page)=>{if(!(await page.locator('#acf-field_hd_model').isVisible())){await page.getByRole('button',{name:'Meta Boxes',exact:true}).focus();await page.keyboard.press('Enter');}await page.locator('#acf-field_hd_model').fill('EDITOR-VERIFIED');await page.getByRole('button',{name:'Save',exact:true}).click();await page.waitForFunction(async()=> (await wp.apiFetch({path:'/wp/v2/hd_product/${id}?context=edit'})).acf.model==='EDITOR-VERIFIED');await page.screenshot({path:'${out}/editor-field.png'});const preview=await page.context().newPage();await preview.goto('${p.urls.primary}/equipment/model/yhd08/');await preview.getByText('EDITOR-VERIFIED',{exact:false}).first().waitFor();await preview.close();return {actualAcfInput:true,saveButton:true,frontend:true};}`);
 // Test text and featured-image persistence using native editor state plus Save.
 result.checks.contentAndImage=call(`async(page)=>{await page.evaluate(image=>{wp.data.dispatch('core/block-editor').insertBlocks(wp.blocks.createBlock('core/paragraph',{content:'EDITOR BODY VERIFIED'}));wp.data.dispatch('core/editor').editPost({featured_media:image});},${site.media.heroMiniExcavator});await page.getByRole('button',{name:'Save',exact:true}).click();await page.waitForFunction(()=>!wp.data.select('core/editor').isEditedPostDirty()&&!wp.data.select('core/editor').isSavingPost());const saved=await page.evaluate(async()=>await wp.apiFetch({path:'/wp/v2/hd_product/${id}?context=edit'}));return {body:saved.content.raw.includes('EDITOR BODY VERIFIED'),image:saved.featured_media,method:'native editor data actions plus actual Save button; not media-picker UI'};}`);
 assert.ok(result.checks.contentAndImage.body);assert.equal(result.checks.contentAndImage.image,site.media.heroMiniExcavator);
 const files={};for(const dir of ['templates','parts'])for(const file of await readdir(join(p.source,'theme',dir)))files[dir+'/'+file]=await readFile(join(p.source,'theme',dir,file),'utf8');files['home']=original.home;
 const patterns=JSON.parse(wp("echo wp_json_encode(array_values(array_filter(WP_Block_Patterns_Registry::get_instance()->get_all_registered(),static fn($p)=>str_starts_with($p['name'],'b2b-equipment/'))));"));for(const pattern of patterns)files[pattern.name]=pattern.content;
 result.checks.blockValidation=call(`async(page)=>await page.evaluate(files=>Object.entries(files).map(([file,raw])=>{let count=0;const errors=[];function walk(bs){for(const b of bs){count++;if(b.isValid===false||!wp.blocks.getBlockType(b.name))errors.push({block:b.name,valid:b.isValid});walk(b.innerBlocks||[]);}}walk(wp.blocks.parse(raw));return {file,count,errors};}),${JSON.stringify(files)})`);
 assert.ok(result.checks.blockValidation.every(f=>f.errors.length===0),'block serialization');
 result.checks.homeAndPattern=call(`async(page)=>{await page.goto('${p.urls.primary}/wp-admin/post.php?post=${home}&action=edit');await page.getByRole('button',{name:'Save',exact:true}).waitFor();await page.waitForFunction(()=>wp.data.select('core/block-editor').getBlocks().length>0);const data=await page.evaluate(content=>{const s=wp.data.select('core/block-editor');const all=[];function walk(bs){for(const b of bs){all.push(b);walk(b.innerBlocks||[]);}}walk(s.getBlocks());const h=all.find(b=>b.name==='core/heading'&&b.attributes.level===1);if(!h)throw Error('heading not found');wp.data.dispatch('core/block-editor').updateBlockAttributes(h.clientId,{content:'EDITOR VERIFIED: Choose your equipment.'});wp.data.dispatch('core/block-editor').insertBlocks(wp.blocks.parse(content));return {beforeCount:all.length};},${JSON.stringify(patterns.find(x=>x.name==='b2b-equipment/selection-guide').content)});await page.getByRole('button',{name:'Save',exact:true}).click();await page.waitForFunction(()=>!wp.data.select('core/editor').isSavingPost()&&!wp.data.select('core/editor').isEditedPostDirty());await page.goto('${p.urls.primary}/');await page.getByRole('heading',{name:'EDITOR VERIFIED: Choose your equipment.',exact:true}).waitFor();await page.getByRole('heading',{name:'Choose for the work ahead.',exact:true}).waitFor();return {...data,patternInserted:true,frontend:true};}`);
 result.checks.categoryUi=call(`async(page)=>{await page.goto('${p.urls.primary}/wp-admin/term.php?taxonomy=hd_category&tag_ID=${term}&post_type=hd_product');await page.locator('#acf-field_b2b_category_layout').selectOption('editorial');await Promise.all([page.waitForNavigation(),page.getByRole('button',{name:'Update',exact:true}).click()]);await page.screenshot({path:'${out}/category-editor.png'});await page.goto('${p.urls.primary}/equipment/family/mini-excavator/');await page.getByText('APPLICATION-LED SELECTION',{exact:true}).waitFor();return {selectAndSave:true,frontend:true};}`);
 await writeFile(out+'/browser.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{
 const data=Buffer.from(JSON.stringify(original)).toString('base64');
 wp(`$v=json_decode(base64_decode('${data}'),true);update_field('field_hd_model',$v['model'],${id});update_post_meta(${id},'_wp_page_template',$v['template']);wp_update_post(['ID'=>${id},'post_content'=>$v['body']]);set_post_thumbnail(${id},$v['image']);wp_update_post(['ID'=>${home},'post_content'=>$v['home']]);update_field('field_b2b_category_layout',$v['layout']?:'catalogue','hd_category_${term}');`);
}
