export const commandMap = [
  {command: 'sites list', projectMode: 'not-loaded', skill: 'wordpress-setup', risk: 'account-read', destructive: false},
  {command: 'sites status', projectMode: 'not-loaded', skill: 'wordpress-setup', risk: 'account-read', destructive: false},
  {command: 'init', projectMode: 'not-loaded', skill: 'wordpress-setup', risk: 'local-write', destructive: false},
  {command: 'adopt', projectMode: 'creates-external', skill: 'wordpress-setup', risk: 'remote-write', destructive: false},
  {command: 'hostinger setup', projectMode: 'any', skill: 'wordpress-setup', risk: 'account-read-or-install', destructive: false},
  {command: 'bootstrap', projectMode: 'any', skill: 'wordpress-setup', risk: 'environment-write', destructive: false},
  {command: 'doctor', projectMode: 'any', skill: 'wordpress-setup', risk: 'read-only', destructive: false},
  {command: 'ssh setup', projectMode: 'any', skill: 'wordpress-setup', risk: 'remote-write', destructive: false},
  {command: 'config', projectMode: 'any', skill: 'wordpress-builder', risk: 'read-only', destructive: false},
  {command: 'project inspect', projectMode: 'source-or-external', skill: 'wordpress-content', risk: 'read-only', destructive: false},
  {command: 'builder install', projectMode: 'source-or-external', skill: 'wordpress-setup', risk: 'scoped-remote-write', destructive: false},
  {command: 'builder status', projectMode: 'source-or-external', skill: 'wordpress-content', risk: 'read-only', destructive: false},
  {command: 'check', projectMode: 'source-or-external', skill: 'wordpress-delivery', risk: 'read-only', destructive: false},
  {command: 'backup', projectMode: 'source-or-external', skill: 'wordpress-delivery', risk: 'read-only', destructive: false},
  {command: 'status', projectMode: 'source-or-external', skill: 'wordpress-content', risk: 'read-only', destructive: false},
  {command: 'edit-page', projectMode: 'source-or-external', skill: 'wordpress-content', risk: 'remote-write', destructive: false},
  {command: 'post push', projectMode: 'source-or-external', skill: 'wordpress-content', risk: 'remote-write', destructive: false},
  {command: 'nav add|remove', projectMode: 'source-or-external', skill: 'wordpress-content', risk: 'remote-write', destructive: false},
  {command: 'nav block plan', projectMode: 'source-or-external', skill: 'wordpress-content', risk: 'local-plan-write', destructive: false},
  {command: 'nav block apply', projectMode: 'source-or-external', skill: 'wordpress-content', risk: 'remote-write-with-rollback', destructive: false},
  {command: 'block-template plan', projectMode: 'source-or-external', skill: 'wordpress-design', risk: 'local-plan-write', destructive: false},
  {command: 'block-template apply', projectMode: 'source-or-external', skill: 'wordpress-design', risk: 'remote-write-with-rollback', destructive: false},
  {command: 'template assign', projectMode: 'source-or-external', skill: 'wordpress-content', risk: 'remote-write', destructive: false},
  {command: 'cms-audit', projectMode: 'source-or-external', skill: 'wordpress-content', risk: 'read-only', destructive: false},
  {command: 'audit-fields', projectMode: 'source-or-external', skill: 'wordpress-content', risk: 'read-only', destructive: false},
  {command: 'editor-audit', projectMode: 'source', skill: 'wordpress-design', risk: 'read-only', destructive: false},
  {command: 'verify', projectMode: 'source-or-external', skill: 'wordpress-delivery', risk: 'read-only', destructive: false},
  {command: 'verify-form', projectMode: 'source-or-external', skill: 'wordpress-delivery', risk: 'remote-test-write', destructive: false},
  {command: 'screenshot', projectMode: 'source-or-external', skill: 'wordpress-delivery', risk: 'read-only', destructive: false},
  {command: 'deploy', projectMode: 'source-only', skill: 'wordpress-delivery', risk: 'remote-write', destructive: true},
  {command: 'media', projectMode: 'source-only', skill: 'wordpress-delivery', risk: 'remote-write', destructive: false},
  {command: 'content', projectMode: 'source-only', skill: 'wordpress-content', risk: 'remote-write', destructive: true},
  {command: 'setup', projectMode: 'source-only', skill: 'wordpress-setup', risk: 'remote-write', destructive: false},
  {command: 'configure-seo', projectMode: 'source-only', skill: 'wordpress-delivery', risk: 'remote-write', destructive: false},
  {command: 'rollback', projectMode: 'source-only', skill: 'wordpress-delivery', risk: 'remote-write', destructive: true},
  {command: 'cache', projectMode: 'source-or-external', skill: 'wordpress-delivery', risk: 'remote-write', destructive: false},
  {command: 'wp', projectMode: 'source-or-external', skill: 'wordpress-content', risk: 'depends-on-arguments', destructive: false},
  {command: 'smtp configure', projectMode: 'source-or-external', skill: 'wordpress-setup', risk: 'remote-write', destructive: false},
  {command: 'credentials rotate', projectMode: 'source-or-external', skill: 'wordpress-setup', risk: 'remote-write', destructive: false},
];
