<?php
// Explicit local design migration. Never shipped in customer theme/plugin assets.
defined('ABSPATH') || exit;
if (!defined('NEW_SITE_REFERENCE_LAB') || home_url() !== 'http://127.0.0.1:9490') throw new RuntimeException('Dedicated design preview required');
function design_p(string $s): string {return '<!-- wp:paragraph --><p>'.esc_html($s).'</p><!-- /wp:paragraph -->';}
function design_h(string $s): string {return '<!-- wp:heading --><h2 class="wp-block-heading">'.esc_html($s).'</h2><!-- /wp:heading -->';}
function design_sections(array $sections): string {$out='';foreach($sections as $heading=>$text)$out.=design_h($heading).design_p($text);return $out;}
update_option('blogname','HONGDA');update_option('blogdescription','Excavators and loaders for the work ahead');update_option('blog_public','0');
$home=(int)get_option('page_on_front');$about=(int)get_option('b2b_about_page');$contact=(int)get_option('b2b_contact_page');
wp_update_post(['ID'=>$home,'post_title'=>'Compact equipment for the work ahead','post_content'=>file_get_contents(__DIR__.'/home.html'),'post_excerpt'=>'Explore excavators and loaders by application, compare configurations and send an equipment enquiry.']);
wp_update_post(['ID'=>$about,'post_title'=>'About HONGDA','post_content'=>file_get_contents(__DIR__.'/about.html'),'post_excerpt'=>'A practical starting point for equipment selection, configuration and purchasing discussions.']);set_post_thumbnail($about,get_post_thumbnail_id($home));
wp_update_post(['ID'=>$contact,'post_title'=>'Tell us about your next project.','post_content'=>'','post_excerpt'=>'Send an equipment enquiry with your application, quantity and destination.']);
update_post_meta($about,'_wp_page_template','company');update_post_meta($contact,'_wp_page_template','enquiry');
$families=[
'mini-excavator'=>['Compact excavators','For access-constrained digging, landscaping and utility work. Compare the operating envelope, transport dimensions and attachment requirements before choosing a model.','access width, turning space and required digging depth'],
'construction-excavator'=>['Construction excavators','For earthmoving and site preparation. Start with the material, required reach and site conditions, then compare machine size and the working range.','material, ground conditions and working reach'],
'wheel-loader'=>['Wheel loaders','For loading, stockpiling and moving loose material. Compare the material density, loading height and space available to manoeuvre.','material density, loading height and travel distance'],
'backhoe-loader'=>['Backhoe loaders','For projects combining loading and excavation. Check both ends of the machine against your digging, loading and transport requirements.','digging requirements, loading tasks and travel between work areas'],
'skid-steer-loader'=>['Skid steer loaders','For compact loading and attachment-led work. Compare operating capacity, working space and the hydraulic needs of the tools you intend to use.','operating capacity, hydraulic requirements and ground surface']];
foreach($families as $slug=>$info){$t=get_term_by('slug',$slug,'hd_category');if($t)wp_update_term($t->term_id,'hd_category',['name'=>$info[0],'description'=>$info[1]]);}
foreach(get_posts(['post_type'=>'hd_product','numberposts'=>-1]) as $product){$terms=wp_get_post_terms($product->ID,'hd_category');$term=$terms[0]??null;$data=$families[$term->slug??'mini-excavator'];$model=get_field('model',$product->ID);$type=$term?$data[0]:'Equipment';
 if($product->post_name==='yhd08')update_post_meta($product->ID,'_wp_page_template','product-editorial');
 $title=$model.' · '.preg_replace('/s$/','',strtolower($type));
 wp_update_post(['ID'=>$product->ID,'post_title'=>$title,'post_excerpt'=>'A starting point for your equipment shortlist. Compare '.$data[2].', then confirm the final configuration for your project.','post_content'=>design_sections([
 'Match the machine to the site'=>'For this equipment family, start with '.$data[2].'. Include site photographs or measured access constraints when discussing the specification.',
 'Confirm the working configuration'=>'Check the machine dimensions, intended attachments and operating conditions together. A model designation alone does not establish whether a configuration will suit the job.',
 'Agree the details before ordering'=>'Request a current specification, attachment compatibility confirmation and applicable documentation. Include your quantity and destination so the enquiry covers the full delivery scope.'
 ])]);
}
$applications=[
'agriculture'=>['Farm & land management','Access between buildings, ground conditions and repetitive handling tasks.','Drainage, material handling and general land maintenance each place different demands on equipment.','Measure access routes and describe ground conditions, material and seasonal working hours.'],
'construction'=>['Construction & site preparation','Match the machine to excavation, loading and access requirements.','Identify the work sequence and the largest material or load to be handled.','Share the required working reach, loading height and constraints around adjacent structures.'],
'demolition'=>['Demolition support','Plan for the material, attachment and site safety requirements.','Machine suitability depends on the task, attachment and the project’s safety plan.','Describe the material and work method; ask for attachment compatibility and appropriate protective equipment.'],
'excavation'=>['Excavation & drainage','Compare reach, digging depth and the space available to work.','Define the trench profile and spoil handling route before selecting a machine.','Include trench depth, access width and the ground conditions to be assessed.'],
'landscaping'=>['Landscaping & grounds','Work around narrow entrances, finished surfaces and existing planting.','Access and surface protection can be as important as machine size.','Provide gate width, turning space and information about the surfaces the machine will cross.'],
'surface-mining'=>['Quarry & material support','Define the material and duty cycle before choosing loading equipment.','Material density and abrasive conditions affect both specification and maintenance planning.','Discuss the loading target, ground surface and required site safety equipment.'],
'snow-removal'=>['Seasonal site maintenance','Specify the working surface, tool and operating environment.','A seasonal attachment needs to be compatible with the selected base machine.','Include working width, surface type, temperature range and the intended attachment.'],
'forestry-logging'=>['Land clearing support','Consider terrain, access and task-specific protection.','Clearing and material movement require a detailed assessment of machine and attachment suitability.','Describe slopes, obstacles and handling tasks. Request written confirmation of suitability.'],
'waste-solutions'=>['Material sorting & handling','Choose against material characteristics and the loading process.','Mixed materials place different demands on attachments, visibility and machine protection.','Include material description, working area and the required loading height.'],
'utility-work'=>['Utility & infrastructure','Prepare for precise access and a defined working envelope.','Plan around existing infrastructure and the site’s required work method.','Share access dimensions, required reach and attachment requirements with the supplier.'],
'material-handling'=>['Loading & stockpiling','Start with material density, loading height and travel distance.','Bucket volume alone is not enough to select a loader. Confirm rated capacities and operating conditions.','Describe the material and loading target, and request the applicable capacity documentation.']];
foreach(get_posts(['post_type'=>'hd_solution','numberposts'=>-1]) as $post){$d=$applications[$post->post_name]??['Equipment applications','Start with the conditions.','Define the work.','Share your requirements.'];wp_update_post(['ID'=>$post->ID,'post_title'=>$d[0],'post_excerpt'=>$d[1],'post_content'=>design_sections(['Understand the job'=>$d[2],'Build a useful equipment brief'=>$d[3],'Review the complete configuration'=>'Compare dimensions, working capacity, attachments and site requirements together. Request current documentation and confirm the final configuration before ordering.'])]);$related=get_field('recommended_families',$post->ID);if($related){$q=get_posts(['post_type'=>'hd_product','numberposts'=>1,'tax_query'=>[['taxonomy'=>'hd_category','terms'=>$related]]]);if($q)set_post_thumbnail($post->ID,get_post_thumbnail_id($q[0]));}}
$guides=[
'mini-excavator-cost-2026'=>['What to include in an excavator quotation','Compare the quotation scope, not only the headline price.','Ask whether the quote includes the selected attachments, documentation, packing and delivery scope.','Specify the model configuration, quantity, destination and preferred delivery terms. Compare offers on the same basis.'],
'mini-skid-steer-weight-guide'=>['Plan transport around the complete machine','Check transport weight, dimensions and the intended loading method.','Account for the installed attachment and any equipment transported with the machine.','Request the configuration-specific transport dimensions and weight. Confirm the carrying vehicle and loading arrangements with the responsible operator.'],
'wheel-loader-brake-systems'=>['Questions to ask about loader operating controls','Understand the controls and request model-specific operating documentation.','Do not infer operating or maintenance procedures from another model.','Ask for the operator manual and the inspection requirements applicable to your configuration. Safety-critical diagnosis belongs with a qualified technician.'],
'excavator-overheating-guide'=>['Prepare a useful equipment service enquiry','Give the service team context instead of guessing at a fault.','Record the model, serial number, operating conditions and any displayed warning.','Follow the operator manual for stopping and making the machine safe. Send the observations to a qualified service contact; do not continue operating to test a suspected fault.'],
'gradall-vs-excavator'=>['Compare machines by the work they need to do','Build a task-based shortlist before comparing equipment categories.','Write down required reach, working depth, ground conditions and access restrictions.','Compare manufacturer documentation for the proposed configurations. Category names alone do not establish suitability or operating limits.'],
'import-excavator-from-china-case'=>['Prepare an equipment import enquiry','Clarify the destination and documentation early in the buying process.','Import requirements depend on the destination, product and configuration.','Provide your destination and ask which documents are available. Verify local requirements with an appropriate import professional before agreeing the order.'],
'9-types-excavator-buckets'=>['Specify an attachment with the machine','A useful attachment enquiry includes the tool and its interface requirements.','Describe the material and the intended task, not only the attachment name.','Confirm coupler dimensions, hydraulic flow and pressure where relevant, and compatibility with the selected machine. Request written confirmation.'],
'start-landscaping-business-equipment'=>['Build a landscaping equipment shortlist','Let recurring jobs and site access guide the shortlist.','List the work you expect to repeat and measure common access constraints.','Compare transport requirements, attachments and service arrangements alongside machine dimensions. Avoid selecting purely on maximum capacity.'],
'what-is-a-backhoe-guide'=>['When to consider a backhoe loader','Compare a combined machine against the tasks on your project.','List how often you need excavation, loading and travel between work areas.','Check the working envelope at both ends, attachment needs and transport constraints. Ask for the specification of the exact proposed configuration.']];
foreach(get_posts(['post_type'=>'post','numberposts'=>-1]) as $post){$d=$guides[$post->post_name]??['Equipment purchasing checklist','Prepare a clear brief.','Define the job.','Request current documentation.'];wp_update_post(['ID'=>$post->ID,'post_title'=>$d[0],'post_excerpt'=>$d[1],'post_content'=>design_sections(['Start with the scope'=>$d[2],'What to ask the supplier'=>$d[3],'Keep a written record'=>'Save the agreed specification, supporting documents and commercial scope together. Before ordering, resolve any mismatch between the quotation and the work the equipment must perform.'])]);set_post_thumbnail($post->ID,get_post_thumbnail_id($home));}
$topics=[
'group'=>['Equipment sourcing scope','Ask which entity supplies the equipment, what the quotation covers and who handles after-sales questions.'],
'about'=>['How to prepare your equipment brief','Describe the job, working environment, access, quantity and destination before selecting a configuration.'],
'certifications'=>['Product documentation to request','Ask for documents applicable to the exact model, configuration and destination. A document for a different product does not establish compliance.'],
'team'=>['Know your points of contact','Agree who handles specification questions, commercial documents, delivery coordination and service enquiries.'],
'parts-components'=>['Parts identification & enquiries','Use the machine model, serial number and applicable parts reference. Include clear photographs when seeking identification.'],
'production-quality'=>['Inspection & acceptance planning','Agree what will be checked, what records will be supplied and how configuration differences will be resolved before dispatch.'],
'warranty'=>['Warranty questions before ordering','Request written coverage, exclusions, claim procedures and responsibilities. No general website statement replaces the terms for your order.'],
'oem-solution'=>['Configuration & branding enquiries','Describe the proposed changes, quantity and intended market. Ask which changes are feasible and what validation is required.'],
'dealer-opportunity'=>['Dealer & fleet enquiries','Include your market, equipment focus and intended purchase scope. Discuss product documentation, parts and service expectations.'],
'payment-delivery'=>['Define the delivery scope','Confirm the delivery destination, packing, shipping responsibilities and the documents included in the quotation.'],
'maintenance'=>['Operating & maintenance documentation','Request the model-specific operator manual and maintenance schedule. Use qualified service support for safety-critical work.'],
'after-sales-service'=>['Prepare a service enquiry','Include the model, serial number, operating conditions and the issue observed. Follow the operator manual to keep the machine safe.'],
'faqs'=>['Equipment buying questions','Begin with the job and destination. Ask about the exact specification, compatible attachments, documentation and delivery scope.'],
'exchange-refund'=>['Order changes & commercial terms','Before placing an order, agree the process for configuration changes, cancellations, discrepancies and any return arrangements in writing.']];
foreach(get_posts(['post_type'=>'page','numberposts'=>-1]) as $post){if(!isset($topics[$post->post_name]))continue;$d=$topics[$post->post_name];wp_update_post(['ID'=>$post->ID,'post_title'=>$d[0],'post_excerpt'=>$d[1],'post_content'=>design_sections(['Prepare the right information'=>$d[1],'Include it in your enquiry'=>'Provide the equipment model when known, the quantity and destination, and the documents or clarification you need. Keep the agreed scope with your quotation.'])]);}
$form=\FluentForm\App\Models\Form::find((int)get_option('hd_enquiry_form_id'));
if($form){$def=json_decode($form->form_fields,true);$def['submitButton']['settings']['button_ui']['text']='Send enquiry';foreach($def['fields'] as &$f){$name=$f['attributes']['name']??'';if($name==='description'){$f['settings']['label']='What equipment do you need?';$f['attributes']['placeholder']='Application, model, quantity and delivery requirements';}if($name==='name')$f['settings']['label']='Your name';}unset($f);$form->form_fields=wp_json_encode($def);$form->save();}
update_option('b2b_design_revision','equipment-studio-v2');
echo 'Updated editable demo content and enquiry labels. No production content changed.';
