import { t } from '../../i18n/runtime';
import type { StaticMessageKey } from '../../i18n/catalog';
/** Display metadata only. Imported skills, prompts, package identities and saved references stay original. */
const keys: Readonly<Record<string, StaticMessageKey>> = {
  "Google Maps 地图找客": 'uiGoogleMapsLeadResearch',
  "按地区寻找商家，采集官网与公开联系方式，导出带来源的客户表。": 'uiFindBusinessesByLocationCollectWebsitesAnd',
  "客户调研": 'uiCustomerResearch',
  "核对客户业务与产品匹配，整理带来源的客户报告。": 'uiCheckCustomerBusinessAndProductFitThen',
  "个性化开发信": 'uiPersonalizedOutreach',
  "从真实客户证据出发，生成简短开发信与跟进草稿。": 'uiUseVerifiedCustomerEvidenceToDraftConcise',
  "网站结构": 'uiWebsiteStructure',
  "梳理网站导航、栏目层级和页面结构。": 'uiOrganizeWebsiteNavigationContentHierarchyAndPage',
  "建站": 'uiWebsite',
  "询盘转化检查": 'uiInquiryConversionReview',
  "找出采购信息与询盘路径缺口，形成可定位的修改建议。": 'uiFindMissingBuyerInformationAndObstaclesIn',
  "B2B 产品页文案": 'uiB2BProductPageCopy',
  "把真实产品资料整理成清楚、可用于建站的文案。": 'uiTurnVerifiedProductInformationIntoClearCopy',
  "On-page SEO 检查": 'uiOnpageSEOReview',
  "检查标题、内容、图片与内链，交付逐项修改建议。": 'uiReviewTitlesContentImagesAndInternalLinks',
  "关键词": 'uiKeywords',
  "页面优化": 'uiOnpageSEO',
  "技术 SEO 审计": 'uiTechnicalSEOAudit',
  "检查单页或有界全站的抓取、重复内容、重定向与索引证据。": 'uiReviewCrawlabilityDuplicateContentRedirectsAndIndexing',
  "技术审计": 'uiTechnicalAudits',
  "外贸社媒内容": 'uiSocialMediaContent',
  "将产品与案例转成平台内容、互动草稿或内容日历。": 'uiTurnProductsAndCaseStudiesIntoSocial',
  "社媒": 'uiSocialMedia',
  "搜索词分析": 'uiSearchTermAnalysis',
  "核对广告搜索词意图和统计口径，输出分类与待观察项。": 'uiCheckAdvertisingSearchIntentAndReportingDefinitions',
  "广告": 'uiAdvertising',
  "否词与误伤检查": 'uiNegativeKeywordReview',
  "检查否词候选是否影响有效业务，生成可复核的清单。": 'uiCheckWhetherProposedNegativeKeywordsCouldBlock',
  "广告文案与落地页": 'uiAdCopyAndLandingPages',
  "根据产品证据生成广告变体，核对落地页承诺。": 'uiCreateAdVariationsFromProductEvidenceAnd',
  "网页转表格": 'uiWebPageToTable',
  "提取网页列表和产品参数，整理成带来源的表格。": 'uiExtractPageListsAndProductSpecificationsInto',
  "表格": 'uiTables',
  "产品对比": 'uiProductComparison',
  "比较多个产品的参数与差异，保留配置和来源。": 'uiCompareProductSpecificationsAndDifferencesWhilePreserving',
  "批注整理": 'uiOrganizeAnnotations',
  "把网页批注整理成可执行的修改与验收清单。": 'uiTurnPageAnnotationsIntoActionableChangesAnd',
  "批注": 'notes',
  "阿里国际站商品研究": 'uiAlibabaProductResearch',
  "筛选实际商品与供应商，保存可核对的采集结果。": 'uiFindRealProductsAndSuppliersAndSave',
  "关键词研究与机会筛选": 'uiKeywordResearchAndOpportunities',
  "从产品种子词扩展目标市场关键词，按真实需求、意图和业务相关性筛选。": 'uiExpandProductSeedKeywordsForYourTarget',
  "Google 搜索结果分析": 'uiGoogleSearchResultsAnalysis',
  "读取目标市场实时 SERP，比较排名页面类型、内容覆盖和可切入问题。": 'uiReadCurrentSearchResultsForYourMarket',
  "SEO 文章简报": 'uiSEOArticleBrief',
  "结合关键词指标和搜索结果，为新文章或现有页面制定有依据的大纲。": 'uiUseKeywordMetricsAndSearchResultsTo',
  "数据驱动 SEO 文章": 'uiDatadrivenSEOArticle',
  "把市场数据、企业资料与 SEO 证据组织成有来源的原创文章。": 'uiCombineMarketDataCompanyInformationAndSEO',
  "关键词驱动 SEO 文章": 'uiKeyworddrivenSEOArticle',
  "从指定关键词的搜索数据和意图出发，完成简报、全文与页面元信息。": 'uiUseKeywordDataAndIntentToCreate',
  "网站 SEO 数据分析": 'uiWebsiteSEOAnalysis',
  "分析域名自然排名、关键词与估算流量，结合页面样本确定改进重点。": 'uiAnalyzeOrganicRankingsKeywordsAndEstimatedTraffic',
  "SEO 竞争对手研究": 'uiSEOCompetitorResearch',
  "发现搜索竞争对手，对比自然排名与关键词布局并提出行动建议。": 'uiFindSearchCompetitorsCompareOrganicRankingsAnd',
  "竞争关键词与内容缺口": 'uiKeywordAndContentGaps',
  "找出竞品有排名而自家站没有排名的关键词，再核实值得补齐的内容。": 'uiFindKeywordsWhereCompetitorsRankAndYour',
  "竞争分析": 'uiCompetitorAnalysis',
  "关键词聚类与内容地图": 'uiKeywordClustersAndContentMap',
  "结合关键词指标和 SERP 重叠规划主题页、子页面与内链。": 'uiUseKeywordMetricsAndSearchResultOverlap',
  "旧文章数据诊断与更新": 'uiContentReviewAndRefresh',
  "对照当前搜索意图和原文证据，更新已有文章并保留可复核修改记录。": 'uiUpdateExistingArticlesAgainstCurrentSearchIntent',
  "内容生产": 'uiContentCreation',
  "SEO 文章工作室": 'uiSEOArticleStudio',
  "从关键词或企业数据出发，按需生成简报、大纲或完整文章。": 'uiUseKeywordsOrCompanyDataToCreate',
  "文章": 'uiPost',
  "竞品与域名分析": 'uiCompetitorAndDomainAnalysis',
  "分析单个网站或比较同行的自然排名、关键词与估算流量。": 'uiAnalyzeAWebsiteOrCompareCompetitorsOrganic',
  "竞品": 'uiCompetitors',
  "域名": 'uiDomain',
  "SEO 数据复盘": 'uiSEOPerformanceReview',
  "比较同口径的自然搜索表现，结合真实站点数据或定时快照形成复盘。": 'uiCompareOrganicSearchPerformanceConsistentlyUsingReal',
  "内容计划与本地化": 'uiContentPlanningAndLocalization',
  "将研究结果变成按目标市场组织的内容日历、页面类型和本地化简报。": 'uiTurnResearchIntoMarketspecificContentCalendarsPage',
  "外链画像与变化": 'uiBacklinkProfileAndChanges',
  "分析引用域、外链、锚文本及供应商索引中的新增丢失，保留样本证据。": 'uiAnalyzeReferringDomainsBacklinksAnchorTextAnd',
  "外链": 'uiBacklinks',
  "外链机会发现": 'uiLinkOpportunityResearch',
  "从同行外链和行业内容中找到相关来源页，现场核实引用或合作机会。": 'uiFindRelevantPagesThroughCompetitorBacklinksAnd',
  "外链联系与跟进": 'uiLinkOutreachAndFollowups',
  "基于已核实的来源页生成个性化联系内容，管理发送、跟进和停止联系记录。": 'uiDraftPersonalizedOutreachFromVerifiedSourcePages',
  "内链与页面结构": 'uiInternalLinksAndSiteStructure',
  "基于实际页面和抓取图给出内链建议，定位深度、断链与可能的孤立页面。": 'uiRecommendInternalLinksFromActualPagesAnd',
  "结构化数据检查": 'uiStructuredDataReview',
  "检查页面实际 JSON-LD 与 Microdata 属性，或根据真实内容生成结构化数据草稿。": 'uiInspectActualJSONLDAndMicrodataOrDraft',
  "国际 SEO 检查": 'uiInternationalSEOReview',
  "核对多语言版本的 hreflang、canonical、语言和跨页回链，定位区域配置问题。": 'uiCheckHreflangCanonicalURLsLanguageAndReciprocal',
  "性能与体验诊断": 'uiPerformanceAndExperienceReview',
  "结合云端 Lighthouse 实验室检测与 CrUX 现场数据，给出有证据的优化清单。": 'uiCombineLighthouseLabChecksAndCrUXField',
  "WordPress 原生区块建页": 'uiWordPressBlockPages',
  "根据企业资料创建可编辑的产品页、案例页、FAQ 和广告落地页。": 'uiCreateEditableProductPagesCaseStudiesFAQs',
  "ACF 产品批量导入": 'uiACFProductImport',
  "读取 Excel 或 CSV，映射已有 ACF 字段并分批创建产品草稿。": 'uiReadExcelOrCSVMapExistingACF',
  "WordPress 图文素材与发布": 'uiWordPressMediaAndPublishing',
  "上传图片或 PDF，设置图片说明、特色图并插入文章。": 'uiUploadImagesOrPDFsSetCaptionsAnd',
  "WPForms 询盘表单": 'uiWPFormsInquiryForms',
  "设计询盘字段，创建表单并嵌入 WordPress 原生区块页面。": 'uiDesignInquiryFieldsCreateFormsAndEmbed',
  "Rank Math 站点 SEO 设置": 'uiRankMathSEOSettings',
  "依据实时站点能力检查并修改 SEO 设置，保留变更前后证据。": 'uiCheckLiveSiteCapabilitiesAndUpdateSEO',
  "产品与种子词、目标国家和语言": 'uiProductsSeedKeywordsTargetCountryAndLanguage',
  "关键词表与机会优先级": 'uiKeywordTableAndPrioritizedOpportunities',
  "查询来源与范围记录": 'uiQuerySourcesAndScope',
  "独立站": 'uiBusinessWebsite',
  "内容": 'uiContent',
  "在设置 → 连接器中连接 DataForSEO。付费查询逐次确认；成功数据在当前任务复用。文章由当前模型生成，交付草稿文件。": 'uiConnectDataForSEOInSettingsConnectorsPaidQueries',
  "目标词、国家、语言与可选目标页": 'uiTargetKeywordCountryLanguageAndOptionalTarget',
  "SERP 样本表与页面规划": 'uiSERPSampleTableAndPagePlan',
  "主题或目标词、产品事实、国家与语言": 'uiTopicOrKeywordProductFactsCountryAnd',
  "写作简报、大纲与资料缺口": 'uiWritingBriefOutlineAndMissingInformation',
  "主题、业务数据或报告、目标市场、品牌资料": 'uiTopicBusinessDataOrReportsTargetMarket',
  "文章草稿、元信息与来源表": 'uiArticleDraftMetadataAndSourceTable',
  "主关键词、国家、语言、产品与受众": 'uiPrimaryKeywordCountryLanguageProductsAndAudience',
  "完整文章草稿、元信息与证据": 'uiCompleteArticleDraftMetadataAndEvidence',
  "网站域名、国家与语言": 'uiWebsiteDomainCountryAndLanguage',
  "域名报告、排名词表和改进计划": 'uiDomainReportRankingKeywordsAndImprovementPlan',
  "自家域名、国家语言与可选竞品": 'uiYourDomainCountryLanguageAndOptionalCompetitors',
  "竞品对比表和行动计划": 'uiCompetitorComparisonAndActionPlan',
  "自家域名、竞品域名、国家与语言": 'uiYourDomainCompetitorDomainsCountryAndLanguage',
  "缺口关键词表与内容优先级": 'uiKeywordGapTableAndContentPriorities',
  "关键词或种子词、目标市场、站点页面清单": 'uiKeywordsOrSeedTermsTargetMarketAnd',
  "主题分组、页面地图与内链计划": 'uiTopicGroupsPageMapAndInternalLinking',
  "原文 URL 或文件、关键词与市场": 'uiOriginalURLOrFileKeywordAndMarket',
  "更新稿、修改记录与资料缺口": 'uiUpdatedDraftChangeLogAndMissingInformation',
  "主题或关键词、国家与语言": 'uiTopicOrKeywordCountryAndLanguage',
  "产品事实、受众和交付目标": 'uiProductFactsAudienceAndDeliveryGoals',
  "简报、大纲或完整文章": 'uiBriefOutlineOrCompleteArticle',
  "元信息与来源记录": 'uiMetadataAndSourceRecords',
  "简报": 'uiBrief',
  "大纲": 'uiOutline',
  "研究模式使用 DataForSEO；文章由当前模型生成。需要保存到 WordPress 时再配置该连接器。默认草稿，发布须明确请求并确认。": 'uiResearchModeUsesDataForSEOTheSelectedModel',
  "域名、国家与语言": 'uiDomainCountryAndLanguage',
  "可选竞争对手与分析范围": 'uiOptionalCompetitorsAndAnalysisScope',
  "域名或竞品报告": 'uiDomainOrCompetitorReport',
  "关键词与机会表": 'uiKeywordAndOpportunityTable',
  "两个时间段与国家/设备口径": 'uiTwoTimePeriodsAndConsistentCountrydeviceFilters',
  "站点授权、历史数据或监测目标": 'uiSiteAuthorizationHistoricalDataOrMonitoringGoals',
  "变化归因与待验证假设": 'uiChangeAttributionAndHypothesesToVerify',
  "快照对照表与后续行动": 'uiSnapshotComparisonAndNextActions',
  "按模式使用现有网页/任务文件或对应连接器。API 付费、发信与发布遵循实际审批；缺数据明确说明，不编造结果。": 'uiUsesExistingWebpagesTaskFilesOrThe',
  "产品事实、市场与语言": 'uiProductFactsMarketAndLanguage',
  "研究数据、产能与时间范围": 'uiResearchDataCapacityAndDateRange',
  "内容日历": 'uiContentCalendar',
  "本地化关键词和页面简报": 'uiLocalizedKeywordsAndPageBriefs',
  "目标域名与日期范围": 'uiTargetDomainAndDateRange',
  "分析数量与已知问题": 'uiAnalysisLimitsAndKnownIssues',
  "外链画像报告": 'uiBacklinkProfileReport',
  "新增丢失及核实清单": 'uiNewAndLostBacklinksWithAVerification',
  "我方域名、产品和真实内容资产": 'uiYourDomainProductsAndExistingContentAssets',
  "同行域名与目标市场": 'uiPeerDomainsAndTargetMarket',
  "核实过的外链候选表": 'uiVerifiedBacklinkProspects',
  "联系切入点与未验证项": 'uiOutreachAnglesAndUnverifiedItems',
  "候选来源页与真实联系人": 'uiCandidateSourcePagesAndRealContacts',
  "我方可引用资产和联系目标": 'uiYourReferenceAssetsAndOutreachGoals',
  "个性化邮件草稿": 'uiPersonalizedEmailDrafts',
  "发送回执与联系状态表": 'uiSendingReceiptsAndContactStatusTable',
  "站点或内容清单": 'uiSiteOrContentInventory',
  "可用抓取任务、sitemap 或页面证据": 'uiAvailableCrawlTaskSitemapOrPageEvidence',
  "内链建议表": 'uiInternalLinkingRecommendations',
  "站点结构问题与范围说明": 'uiSiteStructureIssuesAndScope',
  "页面与业务类型": 'uiPageAndBusinessType',
  "实际产品、文章或企业字段": 'uiActualProductArticleOrCompanyFields',
  "结构化数据问题表": 'uiStructuredDataIssueTable',
  "JSON-LD 草稿及验证步骤": 'uiJSONLDDraftAndValidationSteps',
  "目标国家语言与对应 URL": 'uiTargetCountriesLanguagesAndCorrespondingURLs',
  "页面清单或 sitemap": 'uiPageListOrSitemap',
  "多语言版本矩阵": 'uiLanguageVersionMatrix',
  "跨页问题与修复清单": 'uiCrosspageIssuesAndFixes',
  "公开 URL、移动或桌面目标": 'uiPublicURLAndMobileOrDesktopTarget',
  "性能问题及可选 CrUX 配置": 'uiPerformanceIssuesAndOptionalCrUXConfiguration',
  "性能报告": 'uiPerformanceReport',
  "开发修复优先级与复测条件": 'uiDevelopmentPrioritiesAndRetestConditions',
  "企业资料、页面用途与语言": 'uiCompanyInformationPagePurposeAndLanguage',
  "原生区块页面草稿和预览检查": 'uiNativeBlockPageDraftAndPreviewChecks',
  "设置 → 连接器 → WordPress 配置一次；相关插件须在站点安装并开放所需权限。": 'uiConfigureWordPressOnceInSettingsConnectorsRequired',
  "产品表格、唯一编号、已有ACF内容类型": 'uiProductSpreadsheetUniqueIdentifiersAndExistingACF',
  "字段映射预览、产品草稿和逐行回执": 'uiFieldMappingPreviewProductDraftsAndPerrow',
  "运营": 'uiOperations',
  "原始图片/PDF、正文与说明": 'uiOriginalImagesPDFsBodyTextAndDescriptions',
  "媒体回执、图文文章草稿或发布结果": 'uiMediaReceiptsIllustratedArticleDraftOrPublishing',
  "询盘目标、字段和已有页面": 'uiInquiryGoalsFormFieldsAndExistingPages',
  "表单ID、字段回读和嵌入页面": 'uiFormIDFieldVerificationAndEmbeddedPage',
  "站点SEO问题与修改目标": 'uiSiteSEOIssuesAndChangeGoals',
  "设置差异、回读证据和页面核验": 'uiSettingDifferencesReadbackEvidenceAndPageVerification',
  "地区与商家类型": 'uiLocationAndBusinessTypes',
  "每词数量、联系方式补全选项与美元预算": 'uiResultsPerKeywordContactEnrichmentOptionsAnd',
  "客户 CSV": 'uiCustomerCSV',
  "来源记录与采集状态": 'uiSourceRecordsAndCollectionStatus',
  "地图": 'uiMaps',
  "主动开发": 'uiOutboundProspecting',
  "业务员": 'uiSalesRepresentative',
  "需要在设置 → 连接器中连接 Apify；采集费用由你的 Apify 账户承担。": 'uiConnectApifyInSettingsConnectorsCollectionCosts',
  "客户官网或公司名称": 'uiCustomerWebsiteOrCompanyName',
  "我方产品与目标市场": 'uiYourProductsAndTargetMarket',
  "客户概况与来源": 'uiCustomerProfileAndSources',
  "匹配依据与联系切入点": 'uiEvidenceOfFitAndOutreachAngles',
  "背调": 'uiBackgroundResearch',
  "找客": 'uiProspecting2',
  "使用已有网页或任务资料；不会自动连接外部账户。": 'uiUsesExistingWebpagesOrTaskMaterialsDoes',
  "客户资料": 'uiCustomerInformation',
  "产品卖点与沟通语言": 'uiProductBenefitsAndCommunicationLanguage',
  "主题与正文": 'uiSubjectAndBody',
  "跟进草稿": 'uiFollowupDrafts',
  "邮件": 'uiEmail2',
  "销售": 'uiSales',
  "生成可编辑草稿，不自动发信。": 'uiCreatesEditableDraftsWithoutSendingEmailsAutomatically',
  "网站或页面清单": 'uiWebsiteOrPageList',
  "导航结构与页面来源": 'uiNavigationStructureAndPageSources',
  "导航": 'uiNavigation',
  "产品页或落地页": 'uiProductPageOrLandingPage',
  "目标客户与产品事实": 'uiTargetCustomersAndProductFacts',
  "问题与建议": 'uiIssuesAndRecommendations',
  "页面批注或修改清单": 'uiPageAnnotationsOrChangeList',
  "表单": 'uiForms',
  "产品规格、应用与卖点": 'uiProductSpecificationsApplicationsAndBenefits',
  "页面用途和语言": 'uiPagePurposeAndLanguage',
  "页面文案": 'uiPageCopy',
  "待补资料清单": 'uiMissingInformationChecklist',
  "文案": 'uiCopywriting',
  "当前页面": 'uiCurrentPage',
  "目标词与市场（选填）": 'uiTargetKeywordAndMarketOptional',
  "原值与建议值": 'uiOriginalAndSuggestedValues',
  "证据与修改清单": 'uiEvidenceAndChangeList',
  "目标页面或域名": 'uiTargetPageOrDomain',
  "抓取上限、JS 选项与审计目标": 'uiCrawlLimitJavaScriptOptionsAndAuditGoals',
  "技术问题与修复清单": 'uiTechnicalIssuesAndFixes',
  "覆盖范围和证据文件": 'uiCoverageAndEvidenceFiles',
  "单页 DOM 检查无需 API。全站抓取使用 DataForSEO，真实索引检查使用 Google 站点授权；按模式配置。": 'uiSinglepageDOMChecksNeedNoAPISitewide',
  "真实产品或案例": 'uiRealProductsOrCaseStudies',
  "平台、受众与语言": 'uiPlatformAudienceAndLanguage',
  "平台文案与素材说明": 'uiPlatformCopyAndAssetDescriptions',
  "内容计划或互动草稿": 'uiContentPlanOrInteractionDrafts',
  "输出文案与素材简报，不自动生成视频或发布帖子。": 'uiProducesCopyAndAssetBriefsWithoutAutomatically',
  "搜索词 CSV": 'uiSearchTermCSV',
  "产品范围、日期与转化定义": 'uiProductScopeDatesAndConversionDefinitions',
  "逐行分类": 'uiRowbyrowClassification',
  "统计与待观察清单": 'uiStatisticsAndWatchList',
  "搜索词或否词候选": 'uiSearchTermsOrNegativeKeywordCandidates',
  "业务范围与匹配类型": 'uiBusinessScopeAndMatchTypes',
  "候选与影响依据": 'uiCandidatesAndEvidenceOfImpact',
  "保留观察清单": 'uiItemsToKeepUnderObservation',
  "否定关键词": 'uiNegativeKeywords',
  "不修改广告账户；匹配规则需结合实际平台验证。": 'uiDoesNotModifyAdvertisingAccountsVerifyMatch',
  "产品事实与落地页": 'uiProductFactsAndLandingPage',
  "平台、受众与广告目标": 'uiPlatformAudienceAndAdvertisingGoals',
  "文案变体": 'uiCopyVariations',
  "落地页一致性检查": 'uiLandingPageConsistencyReview',
  "广告素材": 'uiAdCreative',
  "生成草稿；发布、预算调整与图片生成需要另有工具。": 'uiGeneratesDraftsPublishingBudgetChangesAndImage',
  "网页表格或列表": 'uiWebpageTablesOrLists',
  "字段与数量范围": 'uiFieldsAndResultLimits',
  "CSV 与来源记录": 'uiCSVAndSourceRecords',
  "采集": 'uiDataCollection',
  "产品页面或资料": 'uiProductPagesOrMaterials',
  "对比维度": 'uiComparisonDimensions',
  "同口径对比表": 'uiComparisonTableWithConsistentCriteria',
  "产品": 'uiProducts',
  "供应商": 'uiSuppliers',
  "选型": 'uiProductSelection',
  "已附带的网页批注": 'uiAttachedPageAnnotations',
  "修改与验收清单": 'uiChangeAndAcceptanceChecklist',
  "交接": 'uiHandoff',
  "关键词、筛选与数量": 'uiKeywordsFiltersAndResultCount',
  "实际可访问的阿里页面": 'uiAccessibleAlibabaPages',
  "商品表与来源": 'uiProductTableAndSources',
  "阿里国际站": 'uiAlibabacom',
  "商品": 'uiProducts2',
  "网站验证码或登录障碍需用户处理；不等于卖家后台运营。": 'uiCAPTCHAsOrLoginBarriersRequireUserAction',
};
export function builtinText(value: string): string { const key = keys[value]; return key ? t(key) : value; }
